id: AF262BB55
title: 'The Vajra Lute: A Brief Fulfilment for the Guru Practice of Vidyādhara-Assembly'
type: translation
pechas:
- IF0EE4922
- IAA2BE86F
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:32:47.563118
  last_modified_at: 2023-01-04 12:32:47.563132
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  IF0EE4922/5711: 51EC
  IAA2BE86F/D8B4: 51EC
